---
abstract: 'An HTML content extractor with scoring heuristics'
author:
  - 'INA Lintaro <tarao at cpan.org>'
build_requires:
  File::Slurp: 0
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTML-ExtractContent
no_index:
  directory:
    - inc
    - t
requires:
  Class::Accessor::Lvalue::Fast: 0
  Exporter::Lite: 0
  HTML::Entities: 0
  List::Util: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.04
